#!/usr/bin/env bash
#commands to automatically configure a Ubuntu machine
sudo apt -y update
sudo apt -y install nginx
sudo apt install nginx-extras
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a \tlocation /redirect_me {\n\t\trewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/listen 80 default_server;/a \terror_page 404 /404.html;\n\tlocation /404 {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default
sudo sed -i '/types_hash_max_size 2048;/a \tserver_tokens off;\n\tmore_set_headers "X-Served-By: $hostname";' /etc/nginx/nginx.conf
sudo service nginx restart
