#!/usr/bin/env bash
#Install your load balancer
sudo apt update
sudo apt-get install -y haproxy
echo "listen 4376-lb-01" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "bind *:80" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "balance roundrobin" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "server 4376-web-01 54.89.74.48:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "server 4376-web-02 54.227.178.59:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
