#!/usr/bin/env bash
#Bash script that configures the container to be running as nginx user
sudo pkill -f apache2
sudo sed -i 's/8080/80/g' /etc/nginx/sites-available/default
sudo sed -i 's/user nginx/' /etc/nginx/nginx.conf
sudo chmod 777 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
