#!/usr/bin/env bash
#Bash script that configures the container to be running as nginx user
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo sed -i 's/user nginx;/' /etc/nginx/nginx.conf
sudo service nginx restart
